# 数値計算

べき乗は^演算子を用いる。TeXの記法と同じです。

In [1]:
2^10

1024

# 配列の初期化
## 0で初期化した配列を作る

In [2]:
x = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
X = zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

## 乱数がセットされた配列を得る

[0,1)の一様分布からの乱数

In [4]:
x = rand(5)

5-element Array{Float64,1}:
 0.6298092233827697
 0.585428099173906 
 0.885460982620697 
 0.627226587331859 
 0.7166740216395819

標準正規分布から生成

In [5]:
x = randn(3,5)

3×5 Array{Float64,2}:
 -0.658257  -0.594119  -0.621631   0.0526909   0.705025 
  0.105708  -0.864288   1.79676   -1.89428    -1.95236  
 -0.992619   0.94995   -0.513313  -0.197456   -0.0630387

## 型とサイズを指定

In [6]:
x = Vector{Float64}(undef, 5)  #{Type}(undef, サイズ)  undefの場合初期化されない

5-element Array{Float64,1}:
 0.0     
 5.0e-324
 5.0e-324
 5.0e-324
 0.0     

In [7]:
X = Array{Float64}(undef, 2, 3)

2×3 Array{Float64,2}:
 1.51653e-315  1.51653e-315  1.51653e-315
 1.51653e-315  1.51653e-315  1.50054e-315

## 空の配列に値を追加していく

Juliaでは、**配列にpush!で値を追加できます**。確保している領域に空きがなくなると、新たに2倍の領域を確保して、元のデータがコピーされます。リスト（動的配列）のように使える、静的配列です。  
[Julia - 配列の実装について](https://goropikari.hatenablog.com/entry/julia_array_implement)

In [8]:
x = []

0-element Array{Any,1}

In [9]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Any,1}:
 -0.22036679853664262
 -1.511059908249156  
  0.4442319736493192 
 -1.1933765979204016 
  0.9399239400917808 

型を明示する場合

In [10]:
x = Vector{Float64}(undef, 0)

0-element Array{Float64,1}

In [11]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Float64,1}:
  0.46458154881316355  
  0.0031487179222892997
  2.130452673083196    
 -0.9061456943384958   
 -0.5780388009730484   

# 行列演算

## 行列の演算子

転置は'（プライム）

In [12]:
X = randn(5,2)
X'

2×5 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 -0.204436  -0.537384  1.20334   0.26666   1.23356 
 -0.260027   1.26273   0.552061  1.63848  -0.208407

逆行列はinv

In [13]:
X = randn(5,5)
inv(X)

5×5 Array{Float64,2}:
 -0.0940256   2.24851    6.15753  -2.27334   0.359252
  0.378371    4.47374   11.0131   -4.959     1.47053 
 -1.01446    -4.8748   -13.4314    5.43545  -0.904381
 -0.14266     1.41633    2.60892  -0.95963   0.259997
 -0.0763376  -3.06532   -7.09023   3.31076  -0.2486  

行列式はLinearAlgebra.det

In [14]:
using LinearAlgebra
det(X)

0.4992949697273127

トレースはLinearAlgebra.tr

In [15]:
tr(X)

0.7004200372839675

## 行列の積

行列の積は*

In [16]:
X = randn(3,5)
Y = randn(5,3)
X * Y

3×3 Array{Float64,2}:
 -0.254795   2.54189    2.8573 
  1.43373   -1.51562   -1.17948
 -0.982925   0.267613  -2.93276

## 要素ごとの演算

Juliaではドット演算子で要素ごとの演算をbroadcastして効率的に計算してくれる。

In [17]:
X = randn(3,5)
Y = randn(3,5)
X .* Y

3×5 Array{Float64,2}:
 -0.380048  -0.0501754  -0.0128166  -2.93085   -0.0694181
 -0.290673  -0.0653387   0.531812   -1.09543   -0.232865 
  0.579441  -0.324194   -0.812439    0.401573   0.023205 

各要素に関数を適用する場合にもドット演算子を用いることができる。

In [18]:
X

3×5 Array{Float64,2}:
 -0.762116  -0.0337225  0.149456  1.59756   -0.406967 
  0.49032    0.137544   1.6224    3.34001    0.630183 
  0.815295   0.337476   1.03157   0.575382  -0.0254899

In [19]:
exp.(X)

3×5 Array{Float64,2}:
 0.466678  0.96684  1.1612    4.94099  0.665666
 1.63284   1.14745  5.06523  28.2194   1.87795 
 2.25984   1.40141  2.80546   1.77781  0.974832

各要素を二乗する場合

In [20]:
X.^2

3×5 Array{Float64,2}:
 0.580821  0.00113721  0.0223372   2.55221   0.165622   
 0.240414  0.0189184   2.63218    11.1557    0.39713    
 0.664706  0.11389     1.06413     0.331065  0.000649734

1/2乗で元の行列の絶対値になることの確認

In [21]:
(X.^2).^(1/2)

3×5 Array{Float64,2}:
 0.762116  0.0337225  0.149456  1.59756   0.406967 
 0.49032   0.137544   1.6224    3.34001   0.630183 
 0.815295  0.337476   1.03157   0.575382  0.0254899

自作関数を適用する場合

In [22]:
f(x) = 1.0 + x + x^2/2 + x^3/factorial(3)

f (generic function with 1 method)

In [23]:
f.(X)

3×5 Array{Float64,2}:
 0.454519  0.96684  1.16118   4.55323  0.664611
 1.63017   1.14744  4.65023  16.1279   1.87046 
 2.23797   1.40083  2.74659   1.77266  0.974832

# DataFrame

In [24]:
using DataFrames

空のDataFrameを定義して、カラムを追加していく

In [25]:
df = DataFrame()

0×0 DataFrame

In [26]:
df.A = ["abc", "def", "ghi", "jkl", "mno"]
df.B = [2,1,1,2,2]
df.C = [5.5, 6.6, 7.7, 8.8, 9.9]
df.D = rand(5)

5-element Array{Float64,1}:
 0.24875130151997293
 0.15918422190224257
 0.8867736270043787 
 0.2503437842375602 
 0.09972488831760029

first(df, 行数)

In [27]:
first(df, 3)

3×4 DataFrame
│ Row │ A      │ B     │ C       │ D        │
│     │ String │ Int64 │ Float64 │ Float64  │
├─────┼────────┼───────┼─────────┼──────────┤
│ 1   │ abc    │ 2     │ 5.5     │ 0.248751 │
│ 2   │ def    │ 1     │ 6.6     │ 0.159184 │
│ 3   │ ghi    │ 1     │ 7.7     │ 0.886774 │

summary(df)、describe(df)

In [28]:
summary(df)

"5×4 DataFrame"

In [29]:
describe(df)

4×8 DataFrame. Omitted printing of 2 columns
│ Row │ variable │ mean     │ min       │ median   │ max      │ nunique │
│     │ Symbol   │ Union…   │ Any       │ Union…   │ Any      │ Union…  │
├─────┼──────────┼──────────┼───────────┼──────────┼──────────┼─────────┤
│ 1   │ A        │          │ abc       │          │ mno      │ 5       │
│ 2   │ B        │ 1.6      │ 1         │ 2.0      │ 2        │         │
│ 3   │ C        │ 7.7      │ 5.5       │ 7.7      │ 9.9      │         │
│ 4   │ D        │ 0.328956 │ 0.0997249 │ 0.248751 │ 0.886774 │         │

カラムを取り出すには df.カラム名  
**JuliaのDataFrameは特別な型ではなく、各カラムはArrayで格納されている。**

In [30]:
df.D

5-element Array{Float64,1}:
 0.24875130151997293
 0.15918422190224257
 0.8867736270043787 
 0.2503437842375602 
 0.09972488831760029

演算結果を新たにカラムに追加する場合

In [31]:
df.E = @. df.C * df.D

5-element Array{Float64,1}:
 1.3681321583598511
 1.050615864554801 
 6.8281569279337155
 2.20302530129053  
 0.987276394344243 

@.は以降の演算全てにドット演算子を適用するオペレータ

## ソート

In [32]:
sort!(df, [:B, :A])

5×5 DataFrame
│ Row │ A      │ B     │ C       │ D         │ E        │
│     │ String │ Int64 │ Float64 │ Float64   │ Float64  │
├─────┼────────┼───────┼─────────┼───────────┼──────────┤
│ 1   │ def    │ 1     │ 6.6     │ 0.159184  │ 1.05062  │
│ 2   │ ghi    │ 1     │ 7.7     │ 0.886774  │ 6.82816  │
│ 3   │ abc    │ 2     │ 5.5     │ 0.248751  │ 1.36813  │
│ 4   │ jkl    │ 2     │ 8.8     │ 0.250344  │ 2.20303  │
│ 5   │ mno    │ 2     │ 9.9     │ 0.0997249 │ 0.987276 │

## DataFrameのCSVへの書き出し、読み出し

In [33]:
using CSV

In [34]:
df |> CSV.write("test.csv", delim=',', writeheader=true)

"test.csv"

In [35]:
df2 = CSV.read("test.csv")

5×5 DataFrame
│ Row │ A      │ B     │ C       │ D         │ E        │
│     │ String │ Int64 │ Float64 │ Float64   │ Float64  │
├─────┼────────┼───────┼─────────┼───────────┼──────────┤
│ 1   │ def    │ 1     │ 6.6     │ 0.159184  │ 1.05062  │
│ 2   │ ghi    │ 1     │ 7.7     │ 0.886774  │ 6.82816  │
│ 3   │ abc    │ 2     │ 5.5     │ 0.248751  │ 1.36813  │
│ 4   │ jkl    │ 2     │ 8.8     │ 0.250344  │ 2.20303  │
│ 5   │ mno    │ 2     │ 9.9     │ 0.0997249 │ 0.987276 │

## DataFrameに対するQuery処理

In [36]:
using DataFramesMeta

In [39]:
res = @linq df |>
    by([:B], maxD=maximum(:D), sumE=sum(:E)) |>  #GROUP BYで集計
    transform(F = :maxD + :sumE) |> #演算結果で新たなカラムを作る
    select(:B, :maxD, :sumE, :F) |>
    orderby(:B)

2×4 DataFrame
│ Row │ B     │ maxD     │ sumE    │ F       │
│     │ Int64 │ Float64  │ Float64 │ Float64 │
├─────┼───────┼──────────┼─────────┼─────────┤
│ 1   │ 1     │ 0.886774 │ 7.87877 │ 8.76555 │
│ 2   │ 2     │ 0.250344 │ 4.55843 │ 4.80878 │

# SQL

In [40]:
using SQLite

In [41]:
db = SQLite.DB("test.db")

SQLite.DB("test.db")

In [42]:
SQLite.tables(db)

(name = ["test"],)

In [45]:
DBInterface.execute(db, "
    DROP TABLE IF EXISTS
        test
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000033e2c828, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

createtable!などの個別メソッドも用意されているものの、DBInterface.execute(db, query)でクエリを直接書いた方がわかりやすい気がする。

In [46]:
DBInterface.execute(db, "
    CREATE TABLE IF NOT EXISTS
        test(
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            age INTEGER NOT NULL
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000014c21ab8, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [47]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            1,
            'Yamada',
            39
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000033e2a758, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [48]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            2,
            'Suzuki',
            26
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000033e2a2a8, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [49]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            3,
            'Tanaka',
            43
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000033e29df8, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

SELECTの結果をDataFrameで受け取る

In [50]:
res = DBInterface.execute(db, "
    SELECT
        *
    FROM
        test
") |> DataFrame

3×3 DataFrame
│ Row │ id    │ name   │ age   │
│     │ Int64 │ String │ Int64 │
├─────┼───────┼────────┼───────┤
│ 1   │ 1     │ Yamada │ 39    │
│ 2   │ 2     │ Suzuki │ 26    │
│ 3   │ 3     │ Tanaka │ 43    │