# 数値計算

べき乗は^演算子を用いる。TeXの記法と同じです。

In [1]:
2^10

1024

# 配列の初期化
## 0で初期化した配列を作る

In [2]:
x = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
X = zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

## 乱数がセットされた配列を得る

In [4]:
x = rand(5)

5-element Array{Float64,1}:
 0.5234858000972897  
 0.19455144243481826 
 0.1569502548341435  
 0.012190729024491143
 0.46051113163086566 

In [5]:
x = randn(3,5)

3×5 Array{Float64,2}:
 0.0562256  -0.555796  -0.99179    0.187646   0.692685
 0.537727   -1.28742   -0.0411194  1.00428    2.29761 
 0.791349    0.255813  -0.300968   1.05836   -2.10769 

## 型とサイズを指定

In [6]:
x = Vector{Float64}(undef, 5)  #{Type}(undef, サイズ)  undefの場合初期化されない

5-element Array{Float64,1}:
 5.399596e-316   
 3.17727127e-315 
 3.202997306e-315
 0.0             
 0.0             

In [7]:
X = Array{Float64}(undef, 2, 3)

2×3 Array{Float64,2}:
 3.17902e-315  3.17902e-315  3.17902e-315
 3.17902e-315  3.17902e-315  3.17902e-315

## 空の配列に値を追加していく

Juliaでは、**配列にpush!で値を追加できます**。確保している領域に空きがなくなると、新たに2倍の領域を確保して、元のデータがコピーされます。リスト（動的配列）のように使える、静的配列です。  
[Julia - 配列の実装について](https://goropikari.hatenablog.com/entry/julia_array_implement)

In [8]:
x = []

0-element Array{Any,1}

In [9]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Any,1}:
 -0.8876690063456179 
  1.4198701462811019 
 -0.8182721509575773 
 -0.07069636545687535
  0.41400293793669873

型を明示する場合

In [10]:
x = Vector{Float64}(undef, 0)

0-element Array{Float64,1}

In [11]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Float64,1}:
 -3.2758414049085047
 -1.9320962509140776
  0.2970066975541611
  1.8715682429595797
  0.707811512063105 

# 行列演算

## 行列の演算子

転置は'（プライム）

In [12]:
X = randn(5,2)
X'

2×5 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 -0.658137   0.623209  0.358167   1.39925   -0.0680305
  0.585652  -1.0926    0.493261  -0.523088  -1.88419  

逆行列はinv

In [13]:
X = randn(5,5)
inv(X)

5×5 Array{Float64,2}:
  0.191724    0.408692   -0.466866   -0.274715   -0.0384027
 -0.0843087  -0.323171   -0.0388304  -0.221998   -0.39508  
  0.444429    0.453219    0.113448   -0.568479   -0.243403 
  0.357031   -0.202174   -0.0523593  -0.0922051   0.101003 
 -0.0745804   0.0337382  -0.13079    -0.406335    0.170354 

行列式はLinearAlgebra.det

In [14]:
using LinearAlgebra
det(X)

-21.753472370114608

トレースはLinearAlgebra.tr

In [15]:
tr(X)

1.8725660269918392

## 行列の積

行列の積は*

In [16]:
X = randn(3,5)
Y = randn(5,3)
X * Y

3×3 Array{Float64,2}:
 -0.0952309  -1.84744    1.93132 
 -1.29173     3.99825    0.712802
 -0.568271    0.0501161  2.9021  

## 要素ごとの演算

Juliaではドット演算子で要素ごとの演算をbroadcastして効率的に計算してくれる。

In [17]:
X = randn(3,5)
Y = randn(3,5)
X .* Y

3×5 Array{Float64,2}:
 1.76955     -0.265579   2.94132    -1.24868    0.0143779
 0.00398142   0.228647   0.266113   -0.257605  -0.6119   
 1.32726     -0.524431  -0.0201093   0.21593   -0.531546 

各要素に関数を適用する場合にもドット演算子を用いることができる。

In [18]:
X

3×5 Array{Float64,2}:
 -0.868915   -1.27484   -2.38702    0.822604  -1.03152 
  0.0255994   0.454375  -0.74087    0.202256   0.719959
 -1.72615    -0.901505  -0.0498689  0.78526    1.26994 

In [19]:
exp.(X)

3×5 Array{Float64,2}:
 0.419406  0.279477  0.0919033  2.27642  0.356464
 1.02593   1.57519   0.476699   1.22416  2.05435 
 0.177968  0.405958  0.951354   2.19298  3.56065 

各要素を二乗する場合

In [20]:
X.^2

3×5 Array{Float64,2}:
 0.755013     1.62521   5.69786     0.676677   1.06404
 0.000655327  0.206457  0.548888    0.0409073  0.51834
 2.97959      0.812711  0.00248691  0.616633   1.61275

1/2乗で元に戻ることの確認

In [21]:
(X.^2).^(1/2)

3×5 Array{Float64,2}:
 0.868915   1.27484   2.38702    0.822604  1.03152 
 0.0255994  0.454375  0.74087    0.202256  0.719959
 1.72615    0.901505  0.0498689  0.78526   1.26994 

自作関数を適用する場合

In [22]:
f(x) = 1.0 + x + x^2/2 + x^3/factorial(3)

f (generic function with 1 method)

In [23]:
f.(X)

3×5 Array{Float64,2}:
  0.399251   0.192455  -0.804905  2.25371  0.317567
  1.02593    1.57324    0.465798  1.22409  2.04133 
 -0.0935566  0.38274    0.951354  2.17428  3.41767 