# 数値計算

べき乗は^演算子を用いる。TeXの記法と同じです。

In [1]:
2^10

1024

# 配列の初期化
## 0で初期化した配列を作る

In [2]:
x = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
X = zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

## 乱数がセットされた配列を得る

In [4]:
x = rand(5)

5-element Array{Float64,1}:
 0.5234858000972897  
 0.19455144243481826 
 0.1569502548341435  
 0.012190729024491143
 0.46051113163086566 

In [5]:
x = randn(3,5)

3×5 Array{Float64,2}:
 0.0562256  -0.555796  -0.99179    0.187646   0.692685
 0.537727   -1.28742   -0.0411194  1.00428    2.29761 
 0.791349    0.255813  -0.300968   1.05836   -2.10769 

## 型とサイズを指定

In [6]:
x = Vector{Float64}(undef, 5)  #{Type}(undef, サイズ)  undefの場合初期化されない

5-element Array{Float64,1}:
 5.399596e-316   
 3.17727127e-315 
 3.202997306e-315
 0.0             
 0.0             

In [7]:
X = Array{Float64}(undef, 2, 3)

2×3 Array{Float64,2}:
 3.17902e-315  3.17902e-315  3.17902e-315
 3.17902e-315  3.17902e-315  3.17902e-315

## 空の配列に値を追加していく

Juliaでは、**配列にpush!で値を追加できます**。確保している領域に空きがなくなると、新たに2倍の領域を確保して、元のデータがコピーされます。リスト（動的配列）のように使える、静的配列です。  
[Julia - 配列の実装について](https://goropikari.hatenablog.com/entry/julia_array_implement)

In [8]:
x = []

0-element Array{Any,1}

In [9]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Any,1}:
 -0.8876690063456179 
  1.4198701462811019 
 -0.8182721509575773 
 -0.07069636545687535
  0.41400293793669873

型を明示する場合

In [10]:
x = Vector{Float64}(undef, 0)

0-element Array{Float64,1}

In [11]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Float64,1}:
 -3.2758414049085047
 -1.9320962509140776
  0.2970066975541611
  1.8715682429595797
  0.707811512063105 

# 行列演算

## 行列の演算子

転置は'（プライム）

In [12]:
X = randn(5,2)
X'

2×5 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 -0.658137   0.623209  0.358167   1.39925   -0.0680305
  0.585652  -1.0926    0.493261  -0.523088  -1.88419  

逆行列はinv

In [13]:
X = randn(5,5)
inv(X)

5×5 Array{Float64,2}:
  0.191724    0.408692   -0.466866   -0.274715   -0.0384027
 -0.0843087  -0.323171   -0.0388304  -0.221998   -0.39508  
  0.444429    0.453219    0.113448   -0.568479   -0.243403 
  0.357031   -0.202174   -0.0523593  -0.0922051   0.101003 
 -0.0745804   0.0337382  -0.13079    -0.406335    0.170354 

行列式はLinearAlgebra.det

In [14]:
using LinearAlgebra
det(X)

-21.753472370114608

トレースはLinearAlgebra.tr

In [15]:
tr(X)

1.8725660269918392

## 行列の積

行列の積は*

In [16]:
X = randn(3,5)
Y = randn(5,3)
X * Y

3×3 Array{Float64,2}:
 -0.0952309  -1.84744    1.93132 
 -1.29173     3.99825    0.712802
 -0.568271    0.0501161  2.9021  

## 要素ごとの演算

Juliaではドット演算子で要素ごとの演算をbroadcastして効率的に計算してくれる。

In [17]:
X = randn(3,5)
Y = randn(3,5)
X .* Y

3×5 Array{Float64,2}:
 1.76955     -0.265579   2.94132    -1.24868    0.0143779
 0.00398142   0.228647   0.266113   -0.257605  -0.6119   
 1.32726     -0.524431  -0.0201093   0.21593   -0.531546 

各要素に関数を適用する場合にもドット演算子を用いることができる。

In [18]:
X

3×5 Array{Float64,2}:
 -0.868915   -1.27484   -2.38702    0.822604  -1.03152 
  0.0255994   0.454375  -0.74087    0.202256   0.719959
 -1.72615    -0.901505  -0.0498689  0.78526    1.26994 

In [19]:
exp.(X)

3×5 Array{Float64,2}:
 0.419406  0.279477  0.0919033  2.27642  0.356464
 1.02593   1.57519   0.476699   1.22416  2.05435 
 0.177968  0.405958  0.951354   2.19298  3.56065 

各要素を二乗する場合

In [20]:
X.^2

3×5 Array{Float64,2}:
 0.755013     1.62521   5.69786     0.676677   1.06404
 0.000655327  0.206457  0.548888    0.0409073  0.51834
 2.97959      0.812711  0.00248691  0.616633   1.61275

1/2乗で元に戻ることの確認

In [21]:
(X.^2).^(1/2)

3×5 Array{Float64,2}:
 0.868915   1.27484   2.38702    0.822604  1.03152 
 0.0255994  0.454375  0.74087    0.202256  0.719959
 1.72615    0.901505  0.0498689  0.78526   1.26994 

自作関数を適用する場合

In [22]:
f(x) = 1.0 + x + x^2/2 + x^3/factorial(3)

f (generic function with 1 method)

In [23]:
f.(X)

3×5 Array{Float64,2}:
  0.399251   0.192455  -0.804905  2.25371  0.317567
  1.02593    1.57324    0.465798  1.22409  2.04133 
 -0.0935566  0.38274    0.951354  2.17428  3.41767 

# DataFrame

In [42]:
using DataFrames

空のDataFrameを定義して、カラムを追加していく

In [35]:
df = DataFrame()

0×0 DataFrame

In [71]:
df.A = ["abc", "def", "ghi", "jkl", "mno"]
df.B = [2,1,1,2,2]
df.C = [5.5, 6.6, 7.7, 8.8, 9.9]
df.D = rand(5)

5-element Array{Float64,1}:
 0.14530632161396295
 0.23719901716938852
 0.7255255814882302 
 0.03822017982478676
 0.6475762439919988 

first(df, 行数)

In [72]:
first(df, 3)

3×5 DataFrame
│ Row │ A      │ B     │ C       │ D        │ E        │
│     │ String │ Int64 │ Float64 │ Float64  │ Float64  │
├─────┼────────┼───────┼─────────┼──────────┼──────────┤
│ 1   │ abc    │ 2     │ 5.5     │ 0.145306 │ 4.09771  │
│ 2   │ def    │ 1     │ 6.6     │ 0.237199 │ 4.35607  │
│ 3   │ ghi    │ 1     │ 7.7     │ 0.725526 │ 0.662319 │

summary(df)、describe(df)

In [73]:
summary(df)

"5×5 DataFrame"

In [74]:
describe(df)

5×8 DataFrame. Omitted printing of 2 columns
│ Row │ variable │ mean     │ min       │ median   │ max      │ nunique │
│     │ Symbol   │ Union…   │ Any       │ Union…   │ Any      │ Union…  │
├─────┼──────────┼──────────┼───────────┼──────────┼──────────┼─────────┤
│ 1   │ A        │          │ abc       │          │ mno      │ 5       │
│ 2   │ B        │ 1.6      │ 1         │ 2.0      │ 2        │         │
│ 3   │ C        │ 7.7      │ 5.5       │ 7.7      │ 9.9      │         │
│ 4   │ D        │ 0.358765 │ 0.0382202 │ 0.237199 │ 0.725526 │         │
│ 5   │ E        │ 2.44912  │ 0.662319  │ 2.34014  │ 4.35607  │         │

カラムを取り出すには df.カラム名  
**JuliaのDataFrameは特別な型ではなく、各カラムはArrayで格納されている。**

In [68]:
df.D

5-element Array{Float64,1}:
 0.14352460692363622
 0.6208644113620145 
 0.08601539381846424
 0.26592487375741003
 0.44000695430523895

演算結果を新たにカラムに追加する場合

In [69]:
df.E = @. df.C * df.D

5-element Array{Float64,1}:
 0.7893853380799992
 4.097705114989296 
 0.6623185324021746
 2.3401388890652086
 4.356068847621866 

@.は以降の演算全てにドット演算子を適用するオペレータ

## ソート

In [77]:
sort!(df, [:B, :A])

5×5 DataFrame
│ Row │ A      │ B     │ C       │ D         │ E        │
│     │ String │ Int64 │ Float64 │ Float64   │ Float64  │
├─────┼────────┼───────┼─────────┼───────────┼──────────┤
│ 1   │ def    │ 1     │ 6.6     │ 0.237199  │ 4.35607  │
│ 2   │ ghi    │ 1     │ 7.7     │ 0.725526  │ 0.662319 │
│ 3   │ abc    │ 2     │ 5.5     │ 0.145306  │ 4.09771  │
│ 4   │ jkl    │ 2     │ 8.8     │ 0.0382202 │ 2.34014  │
│ 5   │ mno    │ 2     │ 9.9     │ 0.647576  │ 0.789385 │

## DataFrameのCSVへの書き出し、読み出し

In [78]:
using CSV

In [79]:
df |> CSV.write("test.csv", delim=',', writeheader=true)

"test.csv"

In [80]:
df2 = CSV.read("test.csv")

5×5 DataFrame
│ Row │ A      │ B     │ C       │ D         │ E        │
│     │ String │ Int64 │ Float64 │ Float64   │ Float64  │
├─────┼────────┼───────┼─────────┼───────────┼──────────┤
│ 1   │ def    │ 1     │ 6.6     │ 0.237199  │ 4.35607  │
│ 2   │ ghi    │ 1     │ 7.7     │ 0.725526  │ 0.662319 │
│ 3   │ abc    │ 2     │ 5.5     │ 0.145306  │ 4.09771  │
│ 4   │ jkl    │ 2     │ 8.8     │ 0.0382202 │ 2.34014  │
│ 5   │ mno    │ 2     │ 9.9     │ 0.647576  │ 0.789385 │

## DataFrameに対するQuery処理

In [76]:
using DataFramesMeta

In [87]:
res = @linq df |>
    by([:B], maxD=maximum(:D), sumE=sum(:E)) |>  #GroupB
    transform(F = :C + :maxD + :sumE)
    select(:B, :maxD, :sumE) |>
    orderby(:B)

2×3 DataFrame
│ Row │ B     │ maxD     │ sumE    │
│     │ Int64 │ Float64  │ Float64 │
├─────┼───────┼──────────┼─────────┤
│ 1   │ 1     │ 0.725526 │ 5.01839 │
│ 2   │ 2     │ 0.647576 │ 7.22723 │

# SQL

In [88]:
using SQLite

In [89]:
db = SQLite.DB("test.db")

SQLite.DB("test.db")

In [93]:
SQLite.tables(db)

(name = ["test"],)

createtable!などの個別メソッドも用意されているものの、DBInterface.execute(db, query)でクエリを直接書いた方がわかりやすい気がする。

In [96]:
DBInterface.execute(db, "
    CREATE TABLE IF NOT EXISTS
        test(
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            age INTEGER NOT NULL
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000038015b98, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [98]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            1,
            'Yamada',
            39
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000041528d58, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [100]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            2,
            'Suzuki',
            26
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x00000000415275e8, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [101]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            3,
            'Tanaka',
            43
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000041526c88, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

SELECTの結果をDataFrameで受け取る

In [102]:
res = DBInterface.execute(db, "
    SELECT
        *
    FROM
        test
") |> DataFrame

3×3 DataFrame
│ Row │ id    │ name   │ age   │
│     │ Int64 │ String │ Int64 │
├─────┼───────┼────────┼───────┤
│ 1   │ 1     │ Yamada │ 39    │
│ 2   │ 2     │ Suzuki │ 26    │
│ 3   │ 3     │ Tanaka │ 43    │

In [103]:
describe(res)

3×8 DataFrame. Omitted printing of 1 columns
│ Row │ variable │ mean   │ min    │ median │ max    │ nunique │ nmissing │
│     │ Symbol   │ Union… │ Any    │ Union… │ Any    │ Union…  │ Nothing  │
├─────┼──────────┼────────┼────────┼────────┼────────┼─────────┼──────────┤
│ 1   │ id       │ 2.0    │ 1      │ 2.0    │ 3      │         │          │
│ 2   │ name     │        │ Suzuki │        │ Yamada │ 3       │          │
│ 3   │ age      │ 36.0   │ 26     │ 39.0   │ 43     │         │          │