# 数値計算

べき乗は^演算子を用いる。TeXの記法と同じです。

In [1]:
2^10

1024

# 配列の初期化
## 0で初期化した配列を作る

In [2]:
x = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
X = zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

## 乱数がセットされた配列を得る

[0,1)の一様分布からの乱数

In [4]:
x = rand(5)

5-element Array{Float64,1}:
 0.3436758677602165
 0.7890123505056188
 0.8378061847995544
 0.9234298855432035
 0.7085727114294085

標準正規分布から生成

In [5]:
x = randn(3,5)

3×5 Array{Float64,2}:
 0.128382  -0.253082  -1.08487     0.473291    1.33333 
 0.609169  -0.564848   0.00291817  1.94113    -0.715567
 1.53582   -0.215529  -0.776332    0.0941686  -0.207186

## 型とサイズを指定

In [6]:
x = Vector{Float64}(undef, 5)  #{Type}(undef, サイズ)  undefの場合初期化されない

5-element Array{Float64,1}:
 0.0     
 5.0e-324
 5.0e-324
 5.0e-324
 0.0     

In [7]:
X = Array{Float64}(undef, 2, 3)

2×3 Array{Float64,2}:
 1.52721e-315  1.52721e-315  1.52721e-315
 1.52721e-315  1.52721e-315  1.51123e-315

## 空の配列に値を追加していく

Juliaでは、**配列にpush!で値を追加できます**。確保している領域に空きがなくなると、新たに2倍の領域を確保して、元のデータがコピーされます。リスト（動的配列）のように使える、静的配列です。  
[Julia - 配列の実装について](https://goropikari.hatenablog.com/entry/julia_array_implement)

In [8]:
x = []

0-element Array{Any,1}

In [9]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Any,1}:
  0.48505791826339795
 -0.4831493367196783 
 -1.323186332075967  
  0.4160725241511637 
  2.034186295032699  

型を明示する場合

In [10]:
x = Vector{Float64}(undef, 0)

0-element Array{Float64,1}

In [11]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Float64,1}:
 -1.0311982495942953 
  0.43377570761826295
  0.8416054161302576 
 -0.9408239259567001 
  1.0769799807458917 

# 行列演算

## 行列の演算子

転置は'（プライム）

In [12]:
X = randn(5,2)
X'

2×5 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 0.125353  -0.348557   -0.550579  0.907719  -1.05802 
 0.69061    0.0144218  -0.839682  0.579043   0.424488

逆行列はinv

In [13]:
X = randn(5,5)
inv(X)

5×5 Array{Float64,2}:
 -0.674462   0.964614  0.138814  -0.0965425  -0.00617559
 -0.58338    0.135778  0.368629   0.296462    1.04379   
 -1.10129    0.422299  0.210391   0.0531611   1.07117   
 -0.657775   0.613483  0.262985   0.0795641  -0.413172  
  0.806834  -0.315562  0.190504  -0.573869   -0.576539  

行列式はLinearAlgebra.det

In [14]:
using LinearAlgebra
det(X)

6.268256185660456

トレースはLinearAlgebra.tr

In [15]:
tr(X)

1.816289738202393

## 行列の積

行列の積は*

In [16]:
X = randn(3,5)
Y = randn(5,3)
X * Y

3×3 Array{Float64,2}:
  3.65084   -1.71225    1.19353 
 -0.850031   0.884335   0.931988
 -3.17776    1.58577   -0.84558 

## 要素ごとの演算

Juliaではドット演算子で要素ごとの演算をbroadcastして効率的に計算してくれる。

In [17]:
X = randn(3,5)
Y = randn(3,5)
X .* Y

3×5 Array{Float64,2}:
 -1.46833   -0.182993  -0.0172208   1.82119   0.156509
 -0.575683   0.370416  -1.46704    -1.55103  -0.144021
 -1.32182    4.0143    -0.0370846  -0.33965  -1.5281  

各要素に関数を適用する場合にもドット演算子を用いることができる。

In [18]:
X

3×5 Array{Float64,2}:
 -1.04629  -0.543322  0.196649  1.15802    0.270358
  1.47791  -0.474713  1.49672   0.77691   -1.687   
 -1.42632  -4.09071   0.124758  0.114935  -1.16778 

In [19]:
exp.(X)

3×5 Array{Float64,2}:
 0.351239  0.580815   1.21732  3.18361  1.31043 
 4.38379   0.622064   4.46702  2.17474  0.185074
 0.240192  0.0167273  1.13287  1.1218   0.311058

各要素を二乗する場合

In [20]:
X.^2

3×5 Array{Float64,2}:
 1.09472   0.295199  0.038671   1.341      0.0730936
 2.18423   0.225352  2.24017    0.60359    2.84597  
 2.03438  16.7339    0.0155646  0.0132101  1.3637   

1/2乗で元の行列の絶対値になることの確認

In [21]:
(X.^2).^(1/2)

3×5 Array{Float64,2}:
 1.04629  0.543322  0.196649  1.15802   0.270358
 1.47791  0.474713  1.49672   0.77691   1.687   
 1.42632  4.09071   0.124758  0.114935  1.16778 

自作関数を適用する場合

In [22]:
f(x) = 1.0 + x + x^2/2 + x^3/factorial(3)

f (generic function with 1 method)

In [23]:
f.(X)

3×5 Array{Float64,2}:
 0.310173   0.577546  1.21725  3.08734   1.3102   
 4.10805    0.620134  4.17563  2.15686  -0.0642066
 0.107261  -6.13269   1.13286  1.12179   0.248658 

# DataFrame

In [24]:
using DataFrames

空のDataFrameを定義して、カラムを追加していく

In [25]:
df = DataFrame()

0×0 DataFrame

In [26]:
df.A = ["abc", "def", "ghi", "jkl", "mno"]
df.B = [2,1,1,2,2]
df.C = [5.5, 6.6, 7.7, 8.8, 9.9]
df.D = rand(5)

5-element Array{Float64,1}:
 0.2987274294333715 
 0.7825858666460808 
 0.03755414728246609
 0.5115793116232719 
 0.6745891613919339 

first(df, 行数)

In [27]:
first(df, 3)

3×4 DataFrame
│ Row │ A      │ B     │ C       │ D         │
│     │ String │ Int64 │ Float64 │ Float64   │
├─────┼────────┼───────┼─────────┼───────────┤
│ 1   │ abc    │ 2     │ 5.5     │ 0.298727  │
│ 2   │ def    │ 1     │ 6.6     │ 0.782586  │
│ 3   │ ghi    │ 1     │ 7.7     │ 0.0375541 │

summary(df)、describe(df)

In [28]:
summary(df)

"5×4 DataFrame"

In [29]:
describe(df)

4×8 DataFrame. Omitted printing of 2 columns
│ Row │ variable │ mean     │ min       │ median   │ max      │ nunique │
│     │ Symbol   │ Union…   │ Any       │ Union…   │ Any      │ Union…  │
├─────┼──────────┼──────────┼───────────┼──────────┼──────────┼─────────┤
│ 1   │ A        │          │ abc       │          │ mno      │ 5       │
│ 2   │ B        │ 1.6      │ 1         │ 2.0      │ 2        │         │
│ 3   │ C        │ 7.7      │ 5.5       │ 7.7      │ 9.9      │         │
│ 4   │ D        │ 0.461007 │ 0.0375541 │ 0.511579 │ 0.782586 │         │

カラムを取り出すには df.カラム名  
**JuliaのDataFrameは特別な型ではなく、各カラムはArrayで格納されている。**

In [30]:
df.D

5-element Array{Float64,1}:
 0.2987274294333715 
 0.7825858666460808 
 0.03755414728246609
 0.5115793116232719 
 0.6745891613919339 

演算結果を新たにカラムに追加する場合

In [31]:
df.E = @. df.C * df.D

5-element Array{Float64,1}:
 1.6430008618835432
 5.165066719864133 
 0.2891669340749889
 4.501897942284793 
 6.6784326977801465

@.は以降の演算全てにドット演算子を適用するオペレータ

## ソート

In [32]:
sort!(df, [:B, :A])

5×5 DataFrame
│ Row │ A      │ B     │ C       │ D         │ E        │
│     │ String │ Int64 │ Float64 │ Float64   │ Float64  │
├─────┼────────┼───────┼─────────┼───────────┼──────────┤
│ 1   │ def    │ 1     │ 6.6     │ 0.782586  │ 5.16507  │
│ 2   │ ghi    │ 1     │ 7.7     │ 0.0375541 │ 0.289167 │
│ 3   │ abc    │ 2     │ 5.5     │ 0.298727  │ 1.643    │
│ 4   │ jkl    │ 2     │ 8.8     │ 0.511579  │ 4.5019   │
│ 5   │ mno    │ 2     │ 9.9     │ 0.674589  │ 6.67843  │

## DataFrameのCSVへの書き出し、読み出し

In [33]:
using CSV

In [34]:
df |> CSV.write("test.csv", delim=',', writeheader=true)

"test.csv"

In [35]:
df2 = CSV.read("test.csv")

5×5 DataFrame
│ Row │ A      │ B     │ C       │ D         │ E        │
│     │ String │ Int64 │ Float64 │ Float64   │ Float64  │
├─────┼────────┼───────┼─────────┼───────────┼──────────┤
│ 1   │ def    │ 1     │ 6.6     │ 0.782586  │ 5.16507  │
│ 2   │ ghi    │ 1     │ 7.7     │ 0.0375541 │ 0.289167 │
│ 3   │ abc    │ 2     │ 5.5     │ 0.298727  │ 1.643    │
│ 4   │ jkl    │ 2     │ 8.8     │ 0.511579  │ 4.5019   │
│ 5   │ mno    │ 2     │ 9.9     │ 0.674589  │ 6.67843  │

## DataFrameに対するQuery処理

### 条件式による行の抽出

In [36]:
df[df.B .== 1,:]

2×5 DataFrame
│ Row │ A      │ B     │ C       │ D         │ E        │
│     │ String │ Int64 │ Float64 │ Float64   │ Float64  │
├─────┼────────┼───────┼─────────┼───────────┼──────────┤
│ 1   │ def    │ 1     │ 6.6     │ 0.782586  │ 5.16507  │
│ 2   │ ghi    │ 1     │ 7.7     │ 0.0375541 │ 0.289167 │

### DataFramesMetaを用いたパイプラインによるQuery処理

In [37]:
using DataFramesMeta

In [38]:
res = @linq df |>
    by([:B], maxD=maximum(:D), sumE=sum(:E)) |>   #GROUP BYで集計
    transform(F = :maxD + :sumE) |>               #演算結果で新たなカラムを作る
    select(:B, :maxD, :sumE, :F) |>
    orderby(:B)

2×4 DataFrame
│ Row │ B     │ maxD     │ sumE    │ F       │
│     │ Int64 │ Float64  │ Float64 │ Float64 │
├─────┼───────┼──────────┼─────────┼─────────┤
│ 1   │ 1     │ 0.782586 │ 5.45423 │ 6.23682 │
│ 2   │ 2     │ 0.674589 │ 12.8233 │ 13.4979 │

# SQL

In [39]:
using SQLite

In [40]:
db = SQLite.DB("test.db")

SQLite.DB("test.db")

テーブル一覧取得

In [41]:
SQLite.tables(db)

(name = ["test"],)

テーブルのdrop

In [42]:
DBInterface.execute(db, "
    DROP TABLE IF EXISTS
        test
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x000000003989f818, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

createtable!などの個別メソッドも用意されているものの、DBInterface.execute(db, query)でクエリを直接書いた方がわかりやすい気がする。

In [43]:
DBInterface.execute(db, "
    CREATE TABLE IF NOT EXISTS
        test(
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            age INTEGER NOT NULL
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x0000000020279408, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [44]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            1,
            'Yamada',
            39
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x000000003989dbf8, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [45]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            2,
            'Suzuki',
            26
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x000000003989e558, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

In [46]:
DBInterface.execute(db, "
    INSERT INTO test
        VALUES(
            3,
            'Tanaka',
            43
        )
")

SQLite.Query(SQLite.Stmt(SQLite.DB("test.db"), Ptr{Nothing} @0x000000003989d748, Dict{Int64,Any}(), 101), Base.RefValue{Int32}(101), Symbol[], Type[], Dict{Symbol,Int64}())

SELECTの結果をDataFrameで受け取る

In [47]:
res = DBInterface.execute(db, "
    SELECT
        *
    FROM
        test
") |> DataFrame

3×3 DataFrame
│ Row │ id    │ name   │ age   │
│     │ Int64 │ String │ Int64 │
├─────┼───────┼────────┼───────┤
│ 1   │ 1     │ Yamada │ 39    │
│ 2   │ 2     │ Suzuki │ 26    │
│ 3   │ 3     │ Tanaka │ 43    │