# 数値計算

べき乗は^演算子を用いる。TeXの記法と同じです。

In [1]:
2^10

1024

# 配列の初期化
## 0で初期化した配列を作る

In [2]:
x = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
X = zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

## 乱数がセットされた配列を得る

In [4]:
x = rand(5)

5-element Array{Float64,1}:
 0.1854104819490643 
 0.5042650209114115 
 0.16723098549969562
 0.7592700916039781 
 0.9573994684400531 

In [5]:
x = randn(3,5)

3×5 Array{Float64,2}:
 -0.395198  -1.98845   -1.1       -2.93557    -0.270605 
  1.20269    2.19297   -1.12623    0.0509322   0.0631348
 -0.332234  -0.841871   0.201792   0.767502   -0.746662 

## 型とサイズを指定

In [6]:
x = Vector{Float64}(undef, 5)  #{Type}(undef, サイズ)  undefの場合初期化されない

5-element Array{Float64,1}:
 5.3804476e-316  
 5.3804476e-316  
 2.886127157e-315
 2.886127316e-315
 2.809353783e-315

In [7]:
X = Array{Float64}(undef, 2, 3)

2×3 Array{Float64,2}:
 5.38045e-316  2.88613e-315  2.80936e-315
 5.38045e-316  2.88613e-315  1.5353e-315 

## 空の配列に値を追加していく

Juliaでは、**配列にpush!で値を追加できます**。確保している領域に空きがなくなると、新たに2倍の領域を確保して、元のデータがコピーされます。リスト（動的配列）のように使える、静的配列です。  
[Julia - 配列の実装について](https://goropikari.hatenablog.com/entry/julia_array_implement)

In [8]:
x = []

0-element Array{Any,1}

In [9]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Any,1}:
 -0.6720094217511288
  0.4357436858544449
  0.3658087965339545
  1.4658102395690804
 -0.2638071787987569

型を明示する場合

In [10]:
x = Vector{Float64}(undef, 0)

0-element Array{Float64,1}

In [11]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Float64,1}:
  0.3680665204919526 
 -1.1277265731206638 
  0.23613748842423254
  0.575012652848961  
 -0.11681889876036872

# 行列演算

## 行列の演算子

転置は'（プライム）

In [12]:
X = randn(5,2)
X'

2×5 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
  1.44577  0.110402     1.89161  -1.25037   -1.49533
 -0.406    0.00534004  -1.52857   0.265547   1.34148

逆行列はinv

In [13]:
X = randn(5,5)
inv(X)

5×5 Array{Float64,2}:
 -0.983262  0.729372  -0.753523   0.303288   -0.279849 
 -1.37777   1.44735   -2.03603    1.59751    -0.733381 
  0.190365  0.133484   0.619577  -0.386669    0.34798  
  0.176899  1.01891   -0.7323     0.485385   -0.600196 
 -0.105253  0.429157  -0.547327   0.0478875   0.0238216

行列式はLinearAlgebra.det

In [14]:
using LinearAlgebra
X = randn(5,5)
det(X)

-0.12099833422847545

トレースはLinearAlgebra.tr

In [15]:
using LinearAlgebra
X = randn(5,5)
tr(X)

2.831798393825361

## 行列の積

行列の積は*

In [16]:
X = randn(3,5)
Y = randn(5,3)
X * Y

3×3 Array{Float64,2}:
 -0.56908   0.804403  -2.13387 
  1.89211   2.00942    1.54451 
 -0.553489  0.150257   0.331243

## 要素ごとの演算

Juliaではドット演算子で要素ごとの演算をbroadcastして効率的に計算してくれる。

In [17]:
X = randn(3,5)
Y = randn(3,5)
X .* Y

3×5 Array{Float64,2}:
  1.57138   -2.1636    -0.356228   0.0621587  -1.3647  
  0.168985   0.48141   -0.366444  -1.25423    -0.075801
 -0.213664  -0.397774   0.166622   0.414789    0.249783

各要素に関数を適用する場合にもドット演算子を用いることができる。

In [18]:
X

3×5 Array{Float64,2}:
  0.686732  -1.15028  -2.21748   -0.0822121   1.16529  
  0.507798  -1.8208    0.38658    2.66814     0.0480324
 -0.167692   1.47621   0.278711   1.97342    -0.272425 

In [19]:
exp.(X)

3×5 Array{Float64,2}:
 1.98721   0.316547  0.108884   0.921077  3.20685
 1.66163   0.161896  1.47194   14.4131    1.0492 
 0.845614  4.37631   1.32143    7.19524   0.76153

各要素を二乗する場合

In [20]:
X.^2

3×5 Array{Float64,2}:
 0.471601   1.32315  4.9172     0.00675883  1.3579    
 0.257859   3.31532  0.149444   7.11897     0.00230711
 0.0281207  2.17918  0.0776801  3.89439     0.0742155 

1/2乗で元に戻ることの確認

In [21]:
(X.^2).^(1/2)

3×5 Array{Float64,2}:
 0.686732  1.15028  2.21748   0.0822121  1.16529  
 0.507798  1.8208   0.38658   2.66814    0.0480324
 0.167692  1.47621  0.278711  1.97342    0.272425 

自作関数を適用する場合

In [22]:
f(x) = 1.0 + x + x^2/2 + x^3/factorial(3)

f (generic function with 1 method)

In [23]:
f.(X)

3×5 Array{Float64,2}:
 1.97651    0.257626  -0.576172   0.921075  3.10797 
 1.65855   -0.169232   1.47093   10.3934    1.0492  
 0.845582   4.10195    1.32116    6.20149   0.761313