# 数値計算

べき乗は^演算子を用いる。TeXの記法と同じです。

In [29]:
2^10

1024

# 配列の初期化
## 0で初期化した配列を作る

In [3]:
x = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [47]:
X = zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

## 乱数がセットされた配列を得る

In [11]:
x = rand(5)

5-element Array{Float64,1}:
 0.7716100804842903 
 0.5086500838250845 
 0.6554341214654964 
 0.899720664727909  
 0.35409940877615753

In [12]:
x = randn(3,5)

3×5 Array{Float64,2}:
 -0.278478   0.960782    0.487668   0.341565  -0.696059
  1.10178   -0.0850149  -0.206485   0.250391   1.11226 
 -0.774536   0.899902    0.63244   -0.110108   1.71965 

## 空の配列に値を追加していく

Juliaでは、**配列にpush!で値を追加できます**。確保している領域に空きがなくなると、新たに2倍の領域を確保して、元のデータがコピーされます。リスト（動的配列）のように使える、静的配列です。  
[Julia - 配列の実装について](https://goropikari.hatenablog.com/entry/julia_array_implement)

In [19]:
x = Vector{Float64}(undef,0)

0-element Array{Float64,1}

In [20]:
for i in 1:5
    push!(x, randn())
end
x

5-element Array{Float64,1}:
  0.2331858126631971 
 -1.3993387745086678 
 -0.14642277748866456
  0.18702535781451995
  0.11244122736383841

# 行列演算

## 行列の演算子

転置は'（プライム）

In [41]:
X = randn(5,2)
X'

2×5 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 -0.102999  -0.792585   -0.495919  -0.361683   0.125345
 -1.42906   -0.0895204   0.156803   1.33994   -0.245851

逆行列はinv

In [39]:
X = randn(5,5)
inv(X)

5×5 Array{Float64,2}:
 -0.0635136  -0.158072   0.529411    0.226819   0.430768
  1.32321     1.01014   -0.0315077   2.73846   -3.2973  
 -1.05702    -0.899339  -0.659908   -0.909032   1.51897 
 -1.68067    -0.592887  -0.689819   -1.03751    1.10263 
  0.294191   -0.46821    0.782177   -0.500343   0.462275

行列式はLinearAlgebra.det

In [43]:
using LinearAlgebra
X = randn(5,5)
det(X)

-3.143821788652835

トレースはLinearAlgebra.tr

In [46]:
using LinearAlgebra
X = randn(5,5)
tr(X)

0.9398862591982002

## 行列の積

行列の積は*

In [21]:
X = randn(3,5)
Y = randn(5,3)
X * Y

3×3 Array{Float64,2}:
  0.187989  -1.21516   0.52134  
 -0.440576   0.962942  0.0326725
  0.171174  -5.64448   1.0243   

## 要素ごとの演算

Juliaではドット演算子で要素ごとの演算をbroadcastして効率的に計算してくれる。

In [77]:
X = randn(3,5)
Y = randn(3,5)
X .* Y

3×5 Array{Float64,2}:
 -1.06381   -0.189332    0.329952   0.0596341  -0.575622 
  0.145179  -0.0756802  -0.540876  -0.0461721   0.0822439
 -0.661152   1.39419     0.12933    2.21196    -0.607913 

各要素に関数を適用する場合にもドット演算子を用いることができる。

In [78]:
X

3×5 Array{Float64,2}:
  1.22119    0.567679  0.374361  -0.100825    1.63012 
 -0.354934  -0.112343  0.308191  -0.0663351  -1.19064 
  0.969996  -0.929634  0.155349  -1.45684     0.593112

In [79]:
exp.(X)

3×5 Array{Float64,2}:
 3.39121  1.76417   1.45406  0.904091  5.10447 
 0.70122  0.893737  1.36096  0.935817  0.304027
 2.63793  0.394698  1.16807  0.232972  1.80961 

各要素を二乗する場合

In [83]:
X.^2

3×5 Array{Float64,2}:
 1.49129   0.322259  0.140146   0.0101657   2.65728 
 0.125978  0.012621  0.0949814  0.00440034  1.41762 
 0.940892  0.86422   0.0241332  2.12238     0.351782

1/2乗で元に戻ることの確認

In [84]:
(X.^2).^(1/2)

3×5 Array{Float64,2}:
 1.22119   0.567679  0.374361  0.100825   1.63012 
 0.354934  0.112343  0.308191  0.0663351  1.19064 
 0.969996  0.929634  0.155349  1.45684    0.593112

自作関数を適用する場合

In [87]:
f(x) = 1.0 + x + x^2/2 + x^3/factorial(3)

f (generic function with 1 method)

In [88]:
f.(X)

3×5 Array{Float64,2}:
 3.27036   1.7593    1.45318  0.904087   4.6807  
 0.700603  0.893731  1.36056  0.935816   0.236859
 2.59255   0.368574  1.16804  0.0890232  1.80378 