# 数値計算

べき乗は**演算子を用いる

In [57]:
2**10

1024

^はビット単位排他的論理和です。

In [72]:
2^10

8

# 配列の初期化
## 0で初期化した配列を作る

In [9]:
import numpy as np
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

2次元以上の場合は各次元のlengthを**引数ではなくリスト**で渡します。

In [80]:
X = np.zeros([3,5])
X

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 乱数がセットされた配列を得る

In [81]:
x = np.random.rand(5)
x

array([0.67589454, 0.58653259, 0.4241482 , 0.6264963 , 0.04976782])

2次元以上の場合、各次元のlengthを**リストではなく引数**として渡します。

In [82]:
X = np.random.rand(3,5)
X

array([[0.25804133, 0.51906913, 0.22706331, 0.38635988, 0.27016934],
       [0.16333569, 0.5061031 , 0.89618293, 0.43452732, 0.66452677],
       [0.27969012, 0.01229964, 0.50100345, 0.66085721, 0.23846747]])

## 空の配列に値を追加していく

np.appendではnp.appendのたびに配列のコピーが発生してしまうので、Pythonのlistに追加してnp.arrayに変換します。

In [38]:
x = []
type(x)

list

In [39]:
for i in range(5):
    x.append(np.random.randn())
x

[0.09473845075503082,
 1.0366195620769454,
 -0.659305721115643,
 -1.898949764768202,
 -1.9199091436033207]

追加が終わったら、np.arrayに変換する。

In [40]:
x = np.array(x)
x

array([ 0.09473845,  1.03661956, -0.65930572, -1.89894976, -1.91990914])

# 行列演算

## 行列の演算子

転置は.T

In [91]:
X = np.random.randn(5,2)
X.T

array([[ 0.32606172, -0.71812513, -0.48393363, -0.30535355,  1.59734752],
       [-0.4215103 ,  1.68099335,  0.47241539, -0.41902621, -0.14250977]])

逆行列はnp.linalg.inv()

In [93]:
X = np.random.randn(5,5)
np.linalg.inv(X)

array([[-2.30021309e-02,  3.10722413e-01, -2.73162322e-01,
        -2.47840085e-01,  2.19226440e-01],
       [ 6.69369785e-02,  1.06447829e-01, -1.21262890e-01,
         5.29873396e-04, -7.40098066e-01],
       [-4.68022780e-01,  5.23456082e-01, -4.93986262e-01,
         5.65115184e-01,  2.88097414e-01],
       [ 2.16464649e-01, -1.57655260e-01, -3.14321043e-01,
         3.12677072e-01, -3.40535967e-01],
       [ 7.30746005e-01,  1.54835754e-01, -1.02311527e-01,
         3.71237337e-01, -9.64521260e-01]])

行列式はnp.linalg.det()

In [94]:
np.linalg.det(X)

-10.672686806047485

トレースはnp.trace()

In [96]:
np.trace(X)

1.1530706897726941

## 行列の積

np.arrayでは積は@

In [97]:
X = np.random.randn(3,5)
Y = np.random.randn(5,3)
X @ Y

array([[-0.44497587, -2.88784754,  0.15261544],
       [ 3.05026165, -2.69166259, -2.69802374],
       [-2.54511229, -1.01748229,  1.49256817]])

np.matrixでは積は*

In [98]:
X = np.matrix(X)
Y = np.matrix(Y)
X * Y

matrix([[-0.44497587, -2.88784754,  0.15261544],
        [ 3.05026165, -2.69166259, -2.69802374],
        [-2.54511229, -1.01748229,  1.49256817]])

## 要素ごとの演算

np.arrayでは*は要素ごとの積（アダマール積）

In [99]:
X = np.random.randn(3,5)
Y = np.random.randn(3,5)
X * Y

array([[-0.06912543, -0.08432644, -0.17729063,  0.83714485, -0.63125929],
       [-0.11630518, -0.10313143,  0.02173395,  0.11361273,  0.26057096],
       [-0.2569718 ,  0.76103869, -1.00917504, -0.0915772 ,  0.46915449]])

numpyに用意されているユニバーサル関数（配列の各要素に関数を適用して、配列を返す関数）の場合、引数に配列を渡せます。

In [133]:
np.exp(X)

array([[ 1.15435726,  0.65412826,  2.02351212, 11.88690546,  2.92152613],
       [ 2.28896963,  1.13323114,  0.42886482,  0.51635917,  1.35942211],
       [ 2.2444239 ,  2.55512011,  0.25562913,  0.82438976,  0.54732547]])

自作関数を配列の各要素に適用する場合、ユニバーサル関数を作るnp.vectorize, np.frompyfuncを用いる。

In [138]:
import math
def f(x):
    return 1.0 + x + x**2/2 + x**3/math.factorial(3)

In [141]:
x = np.random.randn(5)
np.vectorize(f)(X)

array([[1.15433905, 0.65288302, 2.01159   , 9.06749287, 2.85219376],
       [2.26562353, 1.13322069, 0.41062804, 0.50935274, 1.35902774],
       [2.22330929, 2.51570692, 0.14327963, 0.82433398, 0.54242872]])

In [142]:
np.frompyfunc(f,1,1)(X)

array([[1.1543390505778783, 0.6528830204983905, 2.0115899959606494,
        9.067492869184182, 2.8521937609863373],
       [2.265623527725032, 1.1332206865344288, 0.4106280373142872,
        0.5093527449526516, 1.3590277383609155],
       [2.22330929202048, 2.5157069185945238, 0.14327962651308696,
        0.8243339785591176, 0.5424287159704144]], dtype=object)

一次元配列の場合map関数も使える。mapオブジェクトが返ってくるのでlistに突っ込むなどする。

In [144]:
list(map(f, x))

[1.15795980840982,
 1.4314203628947333,
 0.6517454588827266,
 0.4686848726123124,
 0.49720149127135677]

np.vectorize()はnp.arrayを返してきます。