# 数値計算

べき乗は**演算子を用いる

In [1]:
2**10

1024

^はビット単位排他的論理和です。

In [2]:
2^10

8

# 配列の初期化
## 0で初期化した配列を作る

In [3]:
import numpy as np
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

2次元以上の場合は各次元のlengthを**引数ではなくリスト**で渡します。

In [4]:
X = np.zeros([3,5])
X

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 乱数がセットされた配列を得る

In [5]:
x = np.random.rand(5)
x

array([0.98219848, 0.36744124, 0.05209325, 0.02831856, 0.86170321])

2次元以上の場合、各次元のlengthを**リストではなく引数**として渡します。

In [6]:
X = np.random.rand(3,5)
X

array([[0.9538737 , 0.20829138, 0.71825662, 0.52276164, 0.80964393],
       [0.86031357, 0.76459439, 0.92709556, 0.17543433, 0.07984486],
       [0.20090812, 0.17760609, 0.85757601, 0.65454194, 0.50965233]])

## 空の配列に値を追加していく

np.appendではnp.appendのたびに配列のコピーが発生してしまうので、Pythonのlistに追加してnp.arrayに変換します。

In [7]:
x = []
type(x)

list

In [8]:
for i in range(5):
    x.append(np.random.randn())
x

[-0.6395190775199671,
 -0.14898791034821693,
 -0.6538536791144993,
 2.1237399500812653,
 -0.004059931580496716]

追加が終わったら、np.arrayに変換する。

In [9]:
x = np.array(x)
x

array([-0.63951908, -0.14898791, -0.65385368,  2.12373995, -0.00405993])

# 行列演算

## 行列の演算子

転置は.T

In [10]:
X = np.random.randn(5,2)
X.T

array([[-0.0041619 ,  1.00115216, -0.97243444, -0.61688583,  1.6446958 ],
       [-1.14807121, -0.21381132, -0.19135156,  0.57837083, -1.50328741]])

逆行列はnp.linalg.inv()

In [11]:
X = np.random.randn(5,5)
np.linalg.inv(X)

array([[ 0.25953417, -0.26810579, -0.02110168, -0.01422291, -0.33374295],
       [-0.0303724 ,  0.06460857,  0.29989237,  0.13198379, -0.23508672],
       [ 0.24083174, -0.52176774,  0.23550887,  0.4335634 ,  0.15137836],
       [ 0.34001177,  0.47582082, -0.07695132,  0.36257272, -0.53512994],
       [-1.23568525, -0.47141699,  0.10205474,  1.76591639, -1.37848116]])

行列式はnp.linalg.det()

In [12]:
np.linalg.det(X)

-4.848052338800209

トレースはnp.trace()

In [13]:
np.trace(X)

1.938016722380223

## 行列の積

np.arrayでは積は@

In [14]:
X = np.random.randn(3,5)
Y = np.random.randn(5,3)
X @ Y

array([[-2.44668014, -2.48124914, -0.43931354],
       [-6.4138551 , -5.47893083, -1.91302926],
       [ 0.52776561, -2.31148931,  1.80075872]])

np.matrixでは積は*

In [15]:
X = np.matrix(X)
Y = np.matrix(Y)
X * Y

matrix([[-2.44668014, -2.48124914, -0.43931354],
        [-6.4138551 , -5.47893083, -1.91302926],
        [ 0.52776561, -2.31148931,  1.80075872]])

## 要素ごとの演算

np.arrayでは*は要素ごとの積（アダマール積）

In [16]:
X = np.random.randn(3,5)
Y = np.random.randn(3,5)
X * Y

array([[-3.68988325e-01, -5.55699715e-06, -2.45917496e-01,
         5.87752146e-01,  2.66694332e-01],
       [-8.87635166e-01, -2.73820246e-01, -3.27346125e-01,
         4.83656781e-01,  9.37358495e-03],
       [-1.72718376e-01, -2.12387183e-01, -2.51068729e-03,
         1.04639068e+00,  1.28256532e-02]])

numpyに用意されているユニバーサル関数（配列の各要素に関数を適用して、配列を返す関数）の場合、引数に配列を渡せます。

In [17]:
np.exp(X)

array([[0.44087237, 1.00022033, 0.37798444, 0.33286166, 1.58623271],
       [0.41507765, 0.3879266 , 0.44347645, 1.6741178 , 0.97439873],
       [0.79535575, 1.33492491, 8.76120842, 3.7202834 , 0.98075595]])

自作関数を配列の各要素に適用する場合、ユニバーサル関数を作るnp.vectorize, np.frompyfuncを用いる。

In [18]:
import math
def f(x):
    return 1.0 + x + x**2/2 + x**3/math.factorial(3)

In [19]:
x = np.random.randn(5)
np.vectorize(f)(X)

array([[0.42482169, 1.00022033, 0.34688553, 0.28315237, 1.58415639],
       [0.39398165, 0.35988867, 0.42786598, 1.67084949, 0.97439871],
       [0.79524629, 1.33461715, 7.22934664, 3.55478663, 0.98075594]])

In [20]:
np.frompyfunc(f,1,1)(X)

array([[0.42482169325768093, 1.0002203331387207, 0.3468855264819193,
        0.2831523676080414, 1.5841563855940763],
       [0.39398164907981187, 0.3598886674240378, 0.42786597565022777,
        1.6708494876045197, 0.9743987131696831],
       [0.7952462865866204, 1.3346171548145416, 7.229346644160686,
        3.554786626819949, 0.9807559445623577]], dtype=object)

一次元配列の場合map関数も使える。mapオブジェクトが返ってくるのでlistに突っ込むなどする。

In [21]:
list(map(f, x))

[0.2998933661823099,
 -0.2690546602881254,
 2.1410053548159245,
 4.18748781836257,
 0.3920243327278773]